pushed_model_ingestion_train_path: ""
pushed_model_ingestion_test_path: ""
pushed_model_ingestion_raw_path: r"insuranceprediction\artifact\data_ingestion\2022-07-14-10-19-54\raw_data\Medical_Cost.csv"
 

